### ISSUE TITLE
[🐞] Drop `node@16` support

### ISSUE THREAD

**Issue by BorysShulyak** [BorysShulyak/strapi-plugin-field-formula#111]
### Which component is affected?

Admin

### Describe the bug

-

### Reproduction

-

### System Info

```shell
-
```

**Comment by Dulajdeshan** [comment]
Hi @BorysShulyak I would like to contribute with this issue.

**Comment by BorysShulyak** [comment]
@Dulajdeshan Hi! Sure, it would be so great!

**Comment by BorysShulyak** [comment]
@Dulajdeshan Also, feel free to create an issues or PRs with any ideas on how to improve this plugin!
